name 'repository'
version '0.1.8'
maintainer 'Chris Roberts'
maintainer_email 'chrisroberts.code@gmail.com'
license 'Apache 2.0'
description 'Build package repositories'

depends 'apache2'
depends 'apt'
depends 'gpg', '>= 0.2.2'
